version: '3.8'

networks:
  kafka-net:
    driver: bridge

services:
  inventory-kafka:
    image: apache/kafka:3.9.1
    container_name: inventory-kafka
    networks:
      - kafka-net
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      # Definimos dos listeners: uno EXTERNO para Spring (9092) y uno INTERNO para Conduktor (29092)
      KAFKA_LISTENERS: EXTERNO://0.0.0.0:9092,INTERNO://0.0.0.0:29092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: EXTERNO://localhost:9092,INTERNO://inventory-kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,EXTERNO:PLAINTEXT,INTERNO:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNO
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

  postgres-local:
    image: postgres:17-alpine
    container_name: postgres_local
    # Nota: Quitamos 'profiles' para que se levante automáticamente junto con Conduktor
    networks:
      - kafka-net
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: inventory
      POSTGRES_USER: inventory
      POSTGRES_PASSWORD: inventory
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U inventory"]
      interval: 5s
      timeout: 3s
      retries: 10

  conduktor-local:
    image: conduktor/conduktor-platform:latest
    container_name: conduktor_local
    networks:
      - kafka-net
    ports:
      - "8090:8080"
    environment:
      # Corregido: Ahora apunta a la BD 'inventory' que sí existe
      - CDK_DATABASE_URL=postgresql://inventory:inventory@postgres_local:5432/inventory
      - CDK_ANALYTICS_ENABLED=false
    depends_on:
      postgres-local:
        condition: service_healthy
      inventory-kafka:
        condition: service_started
