spring:
  application:
    name: inventory-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/inventory}
    username: ${DB_USERNAME:inventory}
    password: ${DB_PASSWORD:inventory}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.value.default.type: com.migueljuncalp.eventcontracts.orders.v1.StockOrderEventV1
        spring.json.trusted.packages: com.migueljuncalp.eventcontracts.orders.v1.
    listener:
      ack-mode: record

server:
  port: 8081

inventory:
  # Retardo artificial para visualizar el procesamiento asíncrono. Usa 0s para desactivarlo.
  processing-delay: 2s

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
  api-docs:
    path: /v3/api-docs
